package edu.sdsu.cs.util;

/**
 * Defines the methods required for the class of objects responsible for
 * producing values. Name generators, number generators, ...
 *
 * @author Shawn Healey, San Diego State University
 * @version 1.0
 * @implNote STUDENTS SHALL NOT MODIFY THIS FILE
 */
public interface IValueGenerator<E> {

    /**
     * Produces a value generated by this class.
     *
     * @return A value of E
     */
    E generate();
}
